### ISSUE TITLE
Importprobleme

### ISSUE THREAD

**Issue by besauer** [fitforecommerce/prestacollege#1]
Hallo Martin,

ich habe gerade versucht die Snapshots über PrestaCollege einzuspielen. Meine Version PrestaShop 1.7.6.4. Die Daten kommen aber nicht an (Weder Backend noch Frontend).

Ich bin wie folgt vorgegangen:
1.) Installation Modul
2.) Download Snapshop Produktdaten V. 0.3.
3.) Download Bilder
4.) Import Snapshop Produktdaten V. 0.3.
5.) Import Bilder
6.) Cache gelöscht

Leider wurden die Produkte nicht angezeigt.

Zweite Anlauf, neue (leere) Instanz von PrestaShop
Ich bin wie folgt vorgegangen:
1.) Installation Modul
2.1.) Download Snapshop Produktdaten V. 0.1.
2.2.) Download Snapshop Produktdaten V. 0.2.
2.3.) Download Snapshop Produktdaten V. 0.3.
3.) Download Bilder
4.1.) Import Snapshop Produktdaten V. 0.1.
4.2.) Import Snapshop Produktdaten V. 0.2.
4.3.) Import Snapshop Produktdaten V. 0.3.
5.) Import Bilder
6.) Cache gelöscht

Leider wurden die Produkte nicht angezeigt.

In der Datenbank sind die Datensätze für die Produktdaten vorhanden, soweit ich das sehen konnte auch die Bilder. Das scheint aber nicht anzukommen.

Kannst Du mir sagen, ob ich etwas falsch gemacht habe?

Vielen Dank und viele Grüße
Benedikt

**Comment by ediathome** [comment]
Servus Bernhard!

Probiere es mal in folgender Reihenfolge:

1. Download Datenbank-Snapshot Produktdaten V0.3
2. Download Datei-Snaphshot V0.1
3. Import Datenbank-Snapshot V0.3
4. Import Datei-Snapshot V0.1
5. Cache löschen

Der Fehler ist wahrscheinlich durch das Einspielen der alten Produktdaten (V0.1 und V0.2) entstanden.

Viele Grüße

Martin

<img width="1444" alt="image" src="https://user-images.githubusercontent.com/6861648/95477926-2d4b2100-0989-11eb-9abb-49b1012e600b.png">

**Comment by besauer** [comment]
Super! Danke für Deine Antwort.

...

Ne, geht nicht rein, bzw. wird nicht angezeigt. 

Das Logo geht rein. Soweit ich sehe auch die Datensätze für die Produktdaten, die Produkte werden aber irgendwie nicht aktiviert...

http://www.99-prozent-digital.de/asdsadasdsad/

Hast Du eine Idee, woran das noch liegen könnte?

Meine nächste Idee wäre, dass ich das SQL in einer frischen Instanz direkt einspiele. Sollte ja gehen, oder?

Liebe Grüße
Benni

**Comment by besauer** [comment]
Ich habe die Ursache gefunden: der Standardprefix der Datenbank ist ps_ mein Server hat einen anderen Prefix erzeugt. Den habe ich geändert und der Import hat geklappt. Jetzt hänge ich daran, dass nach dem Import das Mapping des Shops verändert wird, d.h. das Backend ist nicht mehr erreichbar. Ich bleibe dran :)

Das ist der Fehler:
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by besauer** [comment]
Wie geht denn der Pfad in das Backend, indem bei Dir die Installation liegt?

**Comment by ediathome** [comment]
Hallo Benni,
wie Du schon schreibst: am besten dürfte es sein, den Shop noch einmal komplett neu aufzusetzen. Der Backend-Pfad und URL-Mapping wird durch das Einspielen der Daten nicht verändert - da sollte es keine Probleme geben. 

Fehler 500 ist leider nicht sehr aussagekräftig - idealerweise solltest Du den Debug-Modus aktivieren, um aussagekräftigere Fehlermeldungen zu bekommen. [Hier ist eine kurze Anleitung dazu](https://www.prestashop.com/forums/topic/575132-how-to-enable-debug-mode-on-prestashop-17-and-older-versions-turn-on-error-reporting-blank-page/)

Wir können nächste Woche auch mal eine Telefon-/Videosession vereinbaren, um dem Problem auf den Grund zu gehen.

Liebe Grüße

Martin

**Comment by ediathome** [comment]
@besauer Würde Dir evt. ein neues Video-Tutorial weiterhelfen?

**Comment by besauer** [comment]
Vielen Dank, Andreas!

Jetzt habe ich das Problem gefunden. Ich hatte den Shop auf meinem Server automatisch installiert und nicht händisch (via Browser). Auf einer lokalen Instanz mit Xampp funktioniert alles ganz wunderbar. (d.h. war ein Hostingproblem).

Das ganze Ding: Super Arbeit, Martin. Top!

Wie setzt Du den Shop ein und wie entwickelst Du ihn weiter? Würde da gerne mal mit Dir telefonieren und darüber quatschen. Falls Du Lust und Zeit dazu hast, kannst Du mir ja mal schreiben... 

Nochmal Danke und liebe Grüße
Benni
